### ISSUE TITLE
function getDateDifference(start, end)

### ISSUE THREAD

**Issue by jmlpinaEtec** [Servoy/svyUtils#21]
I am using this function to get difference days between two date. But when inside these days is the last sunday of March, there are 36E5 less seconds, so doesn´t count this day. Is there a solution for that?.
Thanks in Advance

**Comment by pruhsert** [comment]
Could you show exactly with what dates you are calling the function, what exactly you get and what you expect to get?

**Comment by jmlpinaEtec** [comment]
getDateDifference('24.03.2018', '25.03.2018').days = 1  
getDateDifference('25.03.2018', '26.03.2018').days = 0  
getDateDifference('26.03.2018', '27.03.2018').days = 1  
getDateDifference('27.03.2018', '28.03.2018').days = 1  

The problem is the time shift from winter to summer. The less hour on 25.03.2016 give 8.28 E7 milliseconds thats is true, but when divide by 1000*60*60 24 result 0 days and 23 hours

**Comment by pruhsert** [comment]
Just to be sure what we are talking about. This

scopes.svyDateUtils.getDateDifference(new Date(2018,2,25), new Date(2018,2,26))

gives me 

{difference:8.28E7,days:0.0,hours:23.0,minutes:0.0,seconds:0.0}

Are you saying it should return days:1, hours:0, minutes:0 and seconds:0?

I think the result is correct because you are really loosing one hour...

**Comment by Woody-Soft** [comment]
But you’re not asking about hours, you are asking for days. And regardless how many hours that day has, it should be still 1 day.
wOOdy


Von: Patrick Ruhsert [mailto:notifications@github.com]
Gesendet: Freitag, 23. März 2018 12:30
An: Servoy/svyUtils <svyUtils@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Servoy/svyUtils] function getDateDifference(start, end) (#21)


Just to be sure what we are talking about. This

scopes.svyDateUtils.getDateDifference(new Date(2018,2,25), new Date(2018,2,26))

gives me

{difference:8.28E7,days:0.0,hours:23.0,minutes:0.0,seconds:0.0}

Are you saying it should return days:1, hours:0, minutes:0 and seconds:0?

I think the result is correct because you are really loosing one hour...

**Comment by pruhsert** [comment]
Not sure I agree. You are asking for the time difference of two given instances in time expressed in days, hours, minutes and seconds. And between these two dates there is no full day (24 hours) difference.

The scope has another function getDayDifference that will return 1 (day) here.

**Comment by Woody-Soft** [comment]
Hmm, yes you’re correct. (as always ☺ )
Using GetDayDifference() ist he correct function if one is interested in pure day numbers.

wOOdy


Von: Patrick Ruhsert [mailto:notifications@github.com]
Gesendet: Freitag, 23. März 2018 12:35
An: Servoy/svyUtils <svyUtils@noreply.github.com>
Cc: Jürgen Wondzinski <juergen@woody-soft.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Servoy/svyUtils] function getDateDifference(start, end) (#21)


Not sure I agree. You are asking for the time difference of two given instances in time expressed in days, hours, minutes and seconds. And between these two dates there is no full day (24 hours) difference.

The scope has another function getDayDifference that will return 1 (day) here.

**Comment by pruhsert** [comment]
If we all agree on that, we can close this issue?

**Comment by jmlpinaEtec** [comment]
Ok I saw the function getDayDifference() but I thought it's similar to getDateDifference().days . 

I will use getDayDifference();

Ok we can close this issue.

Thanks a lot
